name: humhub
description: HumHub Mobile app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.1.7
  dio: ^5.8.0+1
  flutter_riverpod: ^2.1.3
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.4
  flutter_inappwebview: ^6.0.0
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: master
  package_info_plus: ^8.2.1
  app_links: ^6.3.3
  firebase_messaging: ^15.2.7
  firebase_core: ^3.14.0
  flutter_local_notifications: ^18.0.1
  loggy: ^2.0.3
  app_badge_plus: ^1.1.6
  rive: ^0.9.0
  connectivity_plus: ^6.1.3
  swipe_to: ^1.0.2
  shared_preferences: ^2.2.2
  intl: any
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.4
  cached_network_image: ^3.3.1
  talker_flutter: ^4.6.11
  quick_actions: ^1.1.0
  mime: ^2.0.0
  flutter_image_compress: ^2.4.0
  firebase_crashlytics: ^4.3.7
  flutter_svg: ^2.0.9
  flutter_styled_toast: ^2.2.1
  open_file: ^3.5.10
  flutter_keyboard_visibility: ^6.0.0
  internet_connection_checker_plus: ^1.0.1

dependency_overrides:
  url_launcher_android: 6.3.9
  quick_actions_platform_interface:
    git:
      url: https://github.com/PrimozRatej/packages
      path: packages/quick_actions/quick_actions_platform_interface
      ref: main
  quick_actions:
    git:
      url: https://github.com/PrimozRatej/packages
      path: packages/quick_actions/quick_actions
      ref: main
  quick_actions_android:
    git:
      url: https://github.com/PrimozRatej/packages
      path: packages/quick_actions/quick_actions_android
      ref: main
  quick_actions_ios:
    git:
      url: https://github.com/PrimozRatej/packages
      path: packages/quick_actions/quick_actions_ios
      ref: main


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf

  assets:
    - assets/
    - assets/images/
    - assets/images/locale/
    - assets/images/icons/
    - assets/animations/
